### ISSUE TITLE
rpi3 arm packages

### ISSUE THREAD

**Issue by fvzwieten** [dracut-crypt-ssh/dracut-crypt-ssh#10]
I tried to make this work on rpi3, but I can't get it to build properly. Is there a change you could provide arm packages? Willing to help if you don't have an rpi3. I am quite novice at package building and such. Use Fedora 25 on rpi3 (fedberry).

**Comment by artem-sidorenko** [comment]
@fvzwieten I'm sorry, I do not think it would be possible for us to provide regular raspberry builds. I do not have a such setup (and I think @rbu does not have it as well). Missing raspberry pi is not a problem, the solution should be rather an automated build, similar to the CORP builds provided here. I'm not sure if CORP has support for arm builds.

So this might get reality only in the case if somebody finds a good solution and would maintain that.

**Comment by ahesford** [comment]
WONTFIX. Fedora 25 was EOL December 2017. In addition, this is a distribution packaging problem. I'm currently using `dracut-crypt-ssh` on an rpi4 with Void Linux with no special accommodations.
