### ISSUE TITLE
Support for ed25519 keys?

### ISSUE THREAD

**Issue by fmikker** [dracut-crypt-ssh/dracut-crypt-ssh#12]
Hi.
First of all I want to say thank you for a excellent solution!

I've been doing some testing with different key types on the remote machine, and as i use ed25519 per default, I noticed that that key type does not work.

Is there any plans to include support for that key-type?

Verified key types with password that works:
* RSA 4096
* ecdsa-sha2-nistp521 (ECDSA)

**Comment by artem-sidorenko** [comment]
@fmikker thanks for this issue! There is a PR #17 with integration of sshd instead of dropbear. Would this PR resolve this issue?

**Comment by fmikker** [comment]
@artem-sidorenko I believe so, I haven't tried it out tough.

**Comment by tetsumaki** [comment]
I think it would be interesting to replace dropbear by tinyssh.
tinyssh works with ed25519 but tinyssh-convert can be necessary for a better experience.

An example here for dropbear and tinyssh in Arch Linux :
- https://github.com/grazzolini/mkinitcpio-tinyssh
- https://github.com/grazzolini/mkinitcpio-dropbear

**Comment by ahesford** [comment]
ed25519 support was added in 7f7d2f8f9
