### ISSUE TITLE
Cannot Unlock Disks?

### ISSUE THREAD

**Issue by lunarthegrey** [dracut-crypt-ssh/dracut-crypt-ssh#13]
I'm a bit stuck here.. I've done this many times on Debian based systems but I haven't been able to get it to work on CentOS 7. When I boot and try to unlock the disk using console_auth nothing happens. When I see what's going on with console_peek I see this... Note: I'm not just entering my password into the console, I'm typing "console_auth", I then am prompted for the password, and I enter it.

```
-sh-4.2# console_peek                      
         Stopping dracut cmdline hook...
[  OK  ] Stopped dracut initqueue hook.
         Stopping dracut initqueue hook...
[  OK  ] Stopped target Basic System.
[  OK  ] Stopped target System Initialization.
         Starting Setup Virtual Console...
[  OK  ] Started Setup Virtual Console.
[  OK  ] Started Emergency Shell.
         Starting Emergency Shell...
[  OK  ] Reached target Emergency Mode.

Generating "/run/initramfs/rdsosreport.txt"


Entering emergency mode. Exit the shell to continue.
Type "journalctl" to view system logs.
You might want to save "/run/initramfs/rdsosreport.txt" to a USB stick or /boot
after mounting them and attach it to a bug report.


:/# 2LkyGd9ytjaV86GQbKyfJWmPDooZcnVyVC3z4gVzYBSAacFyo7J4tAV2NbWjWWXKeHUStYve9iEB
jG98prTuYajNdZaMyWBH5Ymy
sh: 2LkyGd9ytjaV86GQbKyfJWmPDooZcnVyVC3z4gVzYBSAacFyo7J4tAV2NbWjWWXKeHUStYve9iEB
jG98prTuYajNdZaMyWBH5Ymy: command not found
:/#
```

The long string is my password. Yea don't worry.. This is only a test.

When I try to use "unlock" I get this. 

```
-sh-4.2# unlock
/etc/crypttab is empty or invalid
```

Any ideas on what I could have done wrong here?

**Comment by aimlessadam** [comment]
though it is probably not the reason dracut is bailing out, the bottom issue (with unlock) is because dracut doesn't install crypttab anymore.  There are probably better ways to fix this, but you can try something like this:

echo "install_items=/etc/crypttab" | sudo tee -a  /etc/dracut.conf.d/99-crypttabadd.conf
sudo dracut -f -v

i would toggle selinux to permissive while debugging, and check what "root" device you have for GRUB_CMDLINE_LINUX

**Comment by lunarthegrey** [comment]
Thanks for the response! Everything looks correct to me, I don't think selinux is enabled in initramfs right? I haven't tried your suggestion yet, but I'm baffled as to why console_auth doesn't work. I might just have to use Debian on this server...

**Comment by rbu** [comment]
SELinux is not enabled during the initramfs phase. Based on your console_peek output, it seems that dracut itself did not have the LUKS device configured properly. You need to fix that issue first (it is outside of the realm of dracut-crypt-ssh).

Please refer to the Troubleshooting section of the README: https://github.com/dracut-crypt-ssh/dracut-crypt-ssh#5-troubleshooting-and-debugging

Feel free to reopen if you have more questions and sorry for the delay.
