### ISSUE TITLE
ArchLinux AUR package

### ISSUE THREAD

**Issue by mk-fg** [dracut-crypt-ssh/dracut-crypt-ssh#15]
I'm not the maintainer of the package in question, but was informed that there is one (over email, probably due to being in commit list), as README has that "get in contact" line.

Package(s):

- https://aur.archlinux.org/packages/dracut-crypt-ssh/
- https://aur.archlinux.org/packages/dracut-crypt-ssh-git/

> Here is how it can be installed using an AUR helper called pacaur:
> 
>   pacaur -S dracut-crypt-ssh
> 
> Or for a latest source code build from the github repository:
> 
>   pacaur -S dracut-crypt-ssh-git
> 
> Feel free to add the above instructions to your README.md.

Thanks!

P.S. It's not a huge deal, but maybe README should say how to "contact us" specifically, i.e. open gh issue or email address X, as otherwise reports can go to people who aren't actual maintainers (like me).

**Comment by artem-sidorenko** [comment]
@mk-fg I got this mail as well (and can't find it anymore:) ), I updated the README, many thanks!
