### ISSUE TITLE
documentation: add module to dracut.conf missing

### ISSUE THREAD

**Issue by soul9** [dracut-crypt-ssh/dracut-crypt-ssh#21]
the module should be added to /etc/dracut.conf to work, this is missing from the documentation

**Comment by psi-4ward** [comment]
at least for centos its necessary to add: 

`/etc/dracut.conf.d/90-crypt.conf`
```
add_dracutmodules+=" crypt crypt-ssh "
install_items=/etc/crypttab
```

**Comment by rbu** [comment]
That's not necessary for me on CentOS 7 with dracut 033.502.el7_4.1. In particular, the crypt module and crypttab should be installed by dracut regardless of whether this module is installed or not (if your root filesystem is encrypted).
Can you please provide the output of `dracut -f -v` with the "add_dracutmodules" in the config and without?
