### ISSUE TITLE
Package for Fedora 27 in copr

### ISSUE THREAD

**Issue by Id2ndR** [dracut-crypt-ssh/dracut-crypt-ssh#23]
The packages available in copr are for Fedora 26 and CentOS 7 only.
Can you please rebuild the package for latest version of Fedora?
Thank you.

**Comment by gsauthof** [comment]
Also, adding a description and installation instructions to the copr repo would be great.

Currently they read:

> Description
>
> Description not filled in by author. Very likely personal repository for testing purpose, which you should not use.
>
> Installation Instructions
>
> Instructions not filled in by author. Author knows what to do. Everybody else should avoid this repo.

**Comment by rbu** [comment]
I finally found out which hoops to jump through to get the COPR build working again. You should be able to run
```
# dnf copr enable rbu/dracut-crypt-ssh
# dnf install dracut-crypt-ssh
```
and follow the remaining steps of the README: https://github.com/dracut-crypt-ssh/dracut-crypt-ssh/blob/master/README.md


I also set it up so it creates branches for new Fedora releases when they are branched, however I don't know if it actually triggers a build for them.

Thanks for the reminder with the description, I did fill it in.

**Comment by gsauthof** [comment]
Btw, do you plan to submit this package to the main Fedora repository?

**Comment by rbu** [comment]
I see no blocker to having it there, the current state (COPR repo) is to see if you and others find it useful and are able to get it working.
