### ISSUE TITLE
dropbear-server does not include -m by default.

### ISSUE THREAD

**Issue by Piraty** [dracut-crypt-ssh/dracut-crypt-ssh#25]
## expeted behaviour:
everything works as intended ;)

## actual behaviour:
booting the machine shows dropbear's help output.

## why is this
Dropbear's default does no longer build with option `-m` ("use message of the day"), so using [`dropbear -m`](https://github.com/dracut-crypt-ssh/dracut-crypt-ssh/blob/e256916631724caddad0083552c0cf49cf4b9cfb/modules/60crypt-ssh/dropbear-start.sh#L15) fails with `Invalid option -m`.

- https://github.com/mkj/dropbear/blob/d740dc548924f2faf0934e5f9a4b83d2b5d6902d/default_options.h#L177
- https://github.com/mkj/dropbear/blob/d740dc548924f2faf0934e5f9a4b83d2b5d6902d/svr-runopts.c#L233

## possible solution
remove `-m` from dropbear's command. i tested it, works.

**Comment by rbu** [comment]
I'll get a new release out soon with this change which means the voidlinux hotfix could be removed after upgrading. Thank you.

**Comment by rbu** [comment]
1.0.7 has been released with the patch: https://github.com/dracut-crypt-ssh/dracut-crypt-ssh/releases/tag/v1.0.7
