### ISSUE TITLE
Problem using team interface

### ISSUE THREAD

**Issue by skoroneos** [dracut-crypt-ssh/dracut-crypt-ssh#31]
Greetings.
I used dracut-crypt-ssh on a centos 7 using standard ethernet and dhcp  and it worked fine.
Recently i added 2 gigabit ports in team mode and then added a bridge so the kvm guests i am running can access them.
After changing the network config and making sure it works i try to update using dracut --force but for some reason i can't get an ip from the local dhcp.
Has anyone any experience with similar setup i.e team-> bridged interfaces ?

**Comment by ahesford** [comment]
This module is not responsible for configuring your interface.
