### ISSUE TITLE
broken with dropbearconvert errors after upgrade to openssh-7.8

### ISSUE THREAD

**Issue by sea36** [dracut-crypt-ssh/dracut-crypt-ssh#32]
I've been successfully using dracut-crypt-ssh for a while, but after a recent OS update with Fedora 28 it stopped working.  When I run dracut --force it builds the initramfs image, but I get a message:

dracut: dropbearconvert for RSA key failed

dracut continues and creates the image, but dropbear isn't included.

I think this is down to a change with the format of keys generated by openssh-7.8, compared to earlier versions.

Since the update, private keys generated by ssh-keygen have the header:

-----BEGIN OPENSSH PRIVATE KEY-----

With earlier versions it read:

-----BEGIN RSA PRIVATE KEY-----

I don't think dropbearconvert can understand the new format.

You can restore the old behaviour by adding '-m PEM' as an argument to the ssh-keygen command.

**Comment by Id2ndR** [comment]
Commit https://github.com/dracut-crypt-ssh/dracut-crypt-ssh/pull/33 fix the issue in Fedora 29 too.

**Comment by artem-sidorenko** [comment]
resolved via #33

**Comment by neingeist** [comment]
Could you release a 1.0.8, I hit this issue today with 1.0.7 in the COPR :)

**Comment by utoddl** [comment]
I hit this issue today (March 16, 2020), also with 1.0.7 in COPR. If this is fixed in 1.0.8, it would be nice to have it packaged.

**Comment by galenlynch** [comment]
This still seems to be a problem with the COPR (1.0.7).

**Comment by bmalynovytch** [comment]
You can still manually edit `/usr/lib/dracut/modules.d/60crypt-ssh/module-setup.sh` and replace the following (line 43):

```
@@ -40,7 +40,7 @@ install() {
     
     case ${state} in
       GENERATE )
-        ssh-keygen -t $keyType -f $osshKey -q -N "" || {
+        ssh-keygen -t $keyType -f $osshKey -q -N "" -m PEM || {
           derror "SSH ${msgKeyType} key creation failed"
           rm -rf "$tmpDir"
           return 1
```
(See https://github.com/dracut-crypt-ssh/dracut-crypt-ssh/pull/33/files)
