### ISSUE TITLE
Support Fedora 30

### ISSUE THREAD

**Issue by neingeist** [dracut-crypt-ssh/dracut-crypt-ssh#34]
The package in COPR does not support Fedora 30 because it lacks the following patch:

https://github.com/dracut-crypt-ssh/dracut-crypt-ssh/commit/888343edaa98fb739835c8a447c9bbe465417e5e

This makes logging in and unlocking through `console_auth` work, `unlock` is still broken (I think). This also only fixes GENERATEing the dropbear SSH keys, not SYSTEM and the manual specification of the host keys, because `dropbearconvert` still won't convert the keys.

**Comment by neingeist** [comment]
Hot fixed packages:
* [RPM](http://dnf.bl0rg.net/fedora/30/x86_64/dracut-crypt-ssh-1.0.7-1+mike1.fc30.x86_64.rpm)
* [Source RPM](http://dnf.bl0rg.net/fedora/30/SRPMS/dracut-crypt-ssh-1.0.7-1+mike1.fc30.src.rpm)

**Comment by neingeist** [comment]
👀 @rbu

**Comment by neingeist** [comment]
Latest change in the OpenSSH package breaks dropbearconvert again.

~~~
* Mon Jun 17 2019 Jakub Jelen <jjelen@redhat.com> - 8.0p1-4 + 0.10.3-7
- Compatibility with ibmca engine for ECC
- Generate more modern PEM files using new OpenSSL API
- Provide correct signature types for RSA keys using SHA2 from agent
~~~

**Comment by neingeist** [comment]
My current workaround is to generate (GENERATE in dracut-crypt-ssh config) a RSA key using openssl and use that:

~~~
# diff -u modules/60crypt-ssh/module-setup.sh /usr/lib/dracut/modules.d/60crypt-ssh/module-setup.sh
--- modules/60crypt-ssh/module-setup.sh	2019-06-21 19:57:10.363879987 +0200
+++ /usr/lib/dracut/modules.d/60crypt-ssh/module-setup.sh	2019-06-21 19:56:05.417575987 +0200
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/bash -x
 
 # called by dracut
 check() {
@@ -18,7 +18,7 @@
   [[ -z "${dropbear_port}" ]] && dropbear_port=222
   [[ -z "${dropbear_acl}" ]] && dropbear_acl=/root/.ssh/authorized_keys
   local tmpDir=$(mktemp -d --tmpdir dracut-crypt-ssh.XXXX)
-  local keyTypes="rsa ecdsa"
+  local keyTypes="rsa"
   local genConf="${tmpDir}/crypt-ssh.conf"
   local installConf="/etc/crypt-ssh.conf"
 
@@ -40,12 +40,14 @@
     
     case ${state} in
       GENERATE )
-        ssh-keygen -t $keyType -f $osshKey -q -N "" -m PEM || {
-          derror "SSH ${msgKeyType} key creation failed"
-          rm -rf "$tmpDir"
-          return 1
-        }
-        
+        case ${keyType} in
+          rsa )
+            openssl genrsa -out $osshKey 2048
+            ssh-keygen -e -m PEM -f $osshKey
+            ;;
+          * )
+            ;;
+        esac
         ;;
       SYSTEM )
         local sysKey=/etc/ssh/ssh_host_${keyType}_key
@@ -72,7 +74,7 @@
     esac
     
     #convert the keys from openssh to dropbear format
-    dropbearconvert openssh dropbear $osshKey $dropbearKey > /dev/null 2>&1 || {
+    dropbearconvert openssh dropbear $osshKey $dropbearKey || {
       derror "dropbearconvert for ${msgKeyType} key failed"
       rm -rf "$tmpDir"
       return 1
~~~

**Comment by neingeist** [comment]
One does not see any errors btw, unless running dracut in verbose mode. Not sure if that's a limitation of dracut itself or an issue of dracut-crypt-ssh.

~~~
dracut -fv /boot/initramfs-5.1.11-300.fc30.x86_64.img 5.1.11-300.fc30.x86_64
~~~

**Comment by cfabio** [comment]
I have the same issue, can't unlock a Fedora 30 server anymore.

**Comment by chaseadam** [comment]
thanks for the patch, would love to get this fixed upstream and re-add support for ecdsa

**Comment by chaseadam** [comment]
another workaround is to generate the static keys (recommended anyways).

```
openssl ecparam -name prime256v1 -genkey -noout -out key.pem
openssl genrsa -out key.pem 2048
```

source:
https://developers.yubico.com/PIV/Guides/Generating_keys_using_OpenSSL.html

**Comment by torvitas** [comment]
> another workaround is to generate the static keys (recommended anyways).
> 
> ```
> openssl ecparam -name prime256v1 -genkey -noout -out key.pem
> openssl genrsa -out key.pem 2048
> ```
> 
> source:
> https://developers.yubico.com/PIV/Guides/Generating_keys_using_OpenSSL.html

Works on fedora 31.

**Comment by konstantinblaesi** [comment]
https://github.com/gsauthof/dracut-sshd works with centos 8, I bet it works with fedora

**Comment by artem-sidorenko** [comment]
https://github.com/dracut-crypt-ssh/dracut-crypt-ssh/issues/43

**Comment by ahesford** [comment]
This is a packaging problem and, in the absence of active maintainers interested in supporting Fedora distribution channels, we will not be providing new COPR builds.
