### ISSUE TITLE
Intermittently not getting a network connection on CentOS 7

### ISSUE THREAD

**Issue by drsuser** [dracut-crypt-ssh/dracut-crypt-ssh#35]
We have 5 network interfaces on our system, and I can see dracut iterate through all of them before establishing a connection. Most of the time a connection is established ("link is up") on the interface that is actually connected to the network switch. However every once in a while it fails to establish the connection. What seems to help is hardcoding the interface name in kernel options ("ip=enp1s0:dhcp"), however I would like a more flexible solution where it would use whichever interface is currently physically connected.

**Comment by artem-sidorenko** [comment]
https://github.com/dracut-crypt-ssh/dracut-crypt-ssh/issues/43

**Comment by ahesford** [comment]
This is beyond the scope of this module. Networking is handled in a separate dracut module that is unrelated to this project.
