### ISSUE TITLE
Support openSUSE-Leap-15.1

### ISSUE THREAD

**Issue by kolAflash** [dracut-crypt-ssh/dracut-crypt-ssh#36]
I got this running on openSUSE-Leap-15.1 (short: openSUSE-15.1) with a workaround.

I'd be happy this workaround may result in full openSUSE-15.1 support!

I also opened a ticket to get included in the official openSUSE package sources.
https://bugzilla.opensuse.org/show_bug.cgi?id=1141868

--

### workaround: openSUSE set's the IP too late
Seems like openSUSE-15.1 setups the IP after LUKS decryption. So `rd.neednet=1 ip=dhcp` won't get you network connectivity.
Maybe related: #22

Dirty workaround:
```
--- old/modules/60crypt-ssh/module-setup.sh
+++ new/modules/60crypt-ssh/module-setup.sh
@@ -95,7 +95,7 @@
 
   inst $genConf $installConf
 
-  inst_hook pre-udev 99 "$moddir/dropbear-start.sh"
+  inst_hook initqueue 99 "$moddir/dropbear-start.sh"
   inst_hook pre-pivot 05 "$moddir/dropbear-stop.sh"
 
   inst "${dropbear_acl}" /root/.ssh/authorized_keys
--- modules/60crypt-ssh/dropbear-start.sh
+++ modules/60crypt-ssh/dropbear-start.sh
@@ -12,6 +12,8 @@
     info "  bubblebabble: ${bubble}"
   done
 
+  ip addr add 192.168.0.2/24 dev eth0
+  ip link set eth0 up
   /sbin/dropbear -s -j -k -p ${dropbear_port} -P /tmp/dropbear.pid
   [ $? -gt 0 ] && info 'Dropbear sshd failed to start'
 }
```
Note: `initqueue` instead of `pre-udev`, because network interfaces (e.g. `eth0`) won't be available before `initqueue`.

--

### lblkid patch

There's a patch for lblkid. But I'm not sure if it's really needed or why. (will try to find it out soon)
https://build.opensuse.org/package/view_file/home:Dead_Mozay/dracut-crypt-ssh/libblkid.patch
```
diff --git a/modules/60crypt-ssh/helper/Makefile b/modules/60crypt-ssh/helper/Makefile
index c05bd42..b944568 100644
--- a/modules/60crypt-ssh/helper/Makefile
+++ b/modules/60crypt-ssh/helper/Makefile
@@ -20,7 +20,7 @@ console_auth:	auth.c
 	$(CC) $(CFLAGS) $^ -o $@
 
 unlock:	crypttab.o unlock.o
-	$(CC) $(CFLAGS) -lblkid $^ -o $@
+	$(CC) $(CFLAGS) $^ -lblkid -o $@
 
 crypttab-test: crypttab-test.c crypttab.o crypttab-test-data
 	$(CC) crypttab-test.c $(CFLAGS) crypttab.o -lblkid -o crypttab-test

```

--

### additional note: DON'T include busybox

Some people tried to include busybox for usage in openSUSE-15.1 (I don't know why). But for me that caused just errors and fixed any problems.
(e.g. .sh scripts in the openSUSE initrd are written for "bash", not for the busybox-sh which causes a lot of errors)
https://build.opensuse.org/package/show/home:Dead_Mozay/dracut-crypt-ssh
https://build.opensuse.org/package/show/home:lachs0r/dracut-crypt-ssh

**Comment by artem-sidorenko** [comment]
https://github.com/dracut-crypt-ssh/dracut-crypt-ssh/issues/43

**Comment by ahesford** [comment]
Out-of-order or unpredictably ordered module invocation is a dracut problem. All this module is supposed to do is launch `dropbear` when it runs.

The link ordering change has been made.
