### ISSUE TITLE
unlock crypted volume disk use key-file

### ISSUE THREAD

**Issue by Ankele** [dracut-crypt-ssh/dracut-crypt-ssh#42]
When I install my OS, I chose to encryt my root lv, so I can protect my data even if the disk has been stolen. And this encryption operation should not be known by my user, so I set a rd.luks.key in kernel command line. But this file is plain(It's easy to expose passwords), and I can't add a GPG keyfile to the rootfs because rootfs should be automatically mounted and serviced directly on each boot, however the GPG keyfile ask for password.

The _systemd_ developer suggested that I add a new dracut module, but I really don't know how to do it.
Another way to think about it is if I can execute a custom shell script before rootfs is mounted.

Looking forward to your help!

**Comment by artem-sidorenko** [comment]
https://github.com/dracut-crypt-ssh/dracut-crypt-ssh/issues/43

**Comment by ahesford** [comment]
This seems beyond the scope of dracut-crypt-ssh, but if you PR some changes that align with the basic premise of the module, we will consider adding them.
