### ISSUE TITLE
Maintainers wanted

### ISSUE THREAD

**Issue by artem-sidorenko** [dracut-crypt-ssh/dracut-crypt-ssh#43]
Hey folks,

It's great to see a small active community around this topic :-)

As you probably already noticed, myself and @rbu didn't have much time recently for dracut-crypt-ssh. Sorry for that! But this is life...

My last idea was to align with author of [dracut-sshd](https://github.com/gsauthof/dracut-sshd), to join our forces in order to bring this feature finally upstream to dracut and to have only one solution of this problem. Unfortunately it didn't work out for some reasons I do not understand.

Anyway, if you are looking for maintained alternative of dracut-crypt-ssh - please give [dracut-sshd](https://github.com/gsauthof/dracut-sshd) a try.

If somebody has free resources and wants to take over maintenance of dracut-crypt-ssh, feel free to reach out to me via artem@posteo.de, I'm happy to add new maintainers to the GitHub org.

Artem

**Comment by Heidistein** [comment]
Hey there!
I am somwhat in doubt to step up. I have not that much time on hand.
But still it would be not cool to see this project go away. I have looked at dracut-sshd thoroughly, and I think the approach of this module is more complete and better.
Valid point, dropbear support not ed25519 keys.

One big problem: My C is close to non-existent. The helper module is broken on fedora 30+, and I don't have the knowledge to fix it.

**Comment by dguglielmi** [comment]
Dropbear support for Ed25519 is on master now.

https://github.com/mkj/dropbear/commit/3d12521735e7ef7e48be217af0f27d68e23050a7

**Comment by dm17** [comment]
Great idea!
So long as joining forces / deduplicating work can be done without adding sysD requirement. Plus, according to dracut-sshd documentation, "[dracut-crypt-ssh] comes with an unlock command ... and it's kind of dangerous to use, e.g. when the password prompt times out the password is echoed to the console."

I'm also wondering about the statement "...it is entirely possible to replace the executable files handling your key material, or steal your initramfs's SSH private keys." Why must private keys be kept in initramfs? Also, couldn't some signing / consistency check on boot partition contents prevent most attacks against executable file replacement? Am I correct in thinking [these EFI bundles](https://github.com/zbm-dev/zfsbootmenu/pull/34) would be a fairly optimal remedy?

**Comment by ahesford** [comment]
The project now has a few new maintainers with an interest in keeping things going.

**Comment by dm17** [comment]
> The project now has a few new maintainers with an interest in keeping things going.

If that includes you, then it is awesome news! Thanks @ahesford!
