### ISSUE TITLE
If internet stops working, then how can you get into your computer?

### ISSUE THREAD

**Issue by dm17** [dracut-crypt-ssh/dracut-crypt-ssh#51]
I had this setup and working flawlessly with ZBM. However, now that my only wired router is broken, I see that when it gets to trying dhcp - it never fails and I can never enter the password to login to the physical computer. If this case happens, then of course remotely logging in is out as well. Is there a way I can edit this from ZBM to stop trying to load dropbear so I can just type my password and get in? Eventually if falls into dracut debug - and I type zfsbootmenu - and it just says "waiting for zfsbootmenu initialization" forever.

Sorry for errors & omissions... Will follow up tomorrow after sleep :)
Thanks!

**Comment by dm17** [comment]
I figured out how to use a working router as a dummy, so DHCP succeeds (without internet) and I can get through to the decrypt volume prompt. I think DHCP should fail gracefully and allow those physically at the computer to enter the password, though. Perhaps we can fix it so it does - or at least add a blurb in your tutorial about how to get to the prompt from the dracut debug shell it drops into?

**Comment by ahesford** [comment]
Somehow I missed this issue. This problem is caused by the dracut internal network module, not dracut-crypt-ssh. There is nothing for us to fix here.
