### ISSUE TITLE
Dropbear starts only after first passphrase prompt

### ISSUE THREAD

**Issue by billyJoePiano** [dracut-crypt-ssh/dracut-crypt-ssh#53]
I've searched all over for an answer to this, and nothing seems to solve my problem.  Perhaps I missed something, but I don't think any of the answers from the below-linked issue addressed it.  My problem might have a different cause (not sure)

https://github.com/dracut-crypt-ssh/dracut-crypt-ssh/issues/22

My issue:

When the machine boots, the local console immediately prompts for a passphrase to unlock the drive.  If try to ssh (prior to unlocking the drive) the connection times out.  It seems fair to assume that the dropbear ssh daemon is not running at this point.

If I manually enter the passphrase into the local console, the GRUB process starts, and after that I am able to ssh.  The console prompts for the same passphrase a second time (...yes, I know there's a way around this, but I don't think it's related to my issue...).  If I start an ssh session during this second prompt, I am able to remotely enter the passphrase at this phase, and the system finishes booting (...and the dropbear ssh session disconnects)

So my question is -- how do I get the dropbear ssh daemon to start during that first phase, BEFORE the initial unlocking of the drive?  If I need to be physically present at the machine's console just to get past the first unlock prompt, then it completely defeats the purpose of having remote unlocking.

I know dropbear is working perfectly fine AFTER that phase (and only BEFORE the system is fully booted) because the dropbear ssh key is a unique key, different from the main system's ssh key, and that second prompt is the only time when that ssh key works.

**Comment by billyJoePiano** [comment]
Some system details:

Running CentOS 7.  Fully encrypted root drive and swap using LUKS.

When I setup LUKS, I was following these instructions -- https://devconnected.com/how-to-encrypt-root-filesystem-on-linux/ -- though had to make a few adaptions for CentOS:
- `grub2-mkconfig -o /boot/grub2/grub.cfg` instead of `update-initramfs -u -k all`
- `dracut --force` instead of `update-initramfs -u -k all`
- After A LOT of trial and error, I figured out the drive directives needed for LUKS to work smoothly under CentOS, which are different than the Ubuntu tutorial suggested.  On reboot it was dropping me into the dracut emergency shell after the second passphrase prompt, due to the Logical-volume group not being auto-mounted.  I had to manually run `lvm vgchange -ay` and then create a symlink from the logical volume to /dev/root (at which point I could exit the emergency shell and it would boot normally).  Turns out the main issue (in addition to some tweaks to the drive directives) was including ` rd.auto=1` in the  GRUB_CMDLINE_LINUX directives.

There's an unused 512MB FAT partition that (in theory) could be used as a Windows boot partition, but I doubt I would ever need it.  Maybe this partition could be reformatted as a cleartext ext4 (?) drive to temporarily load GRUB and start the dropbear ssh daemon???

**Comment by billyJoePiano** [comment]
Also, just to address some of the common remedies already suggested:

- In /etc/default/grub, the order of the GRUB_CMDLINE_LINUX="..." directives is as suggested (partial screenshot below).  All the network interface/ip configs seem to be working fine during that second phase of boot, and are placed prior to any of the drive/volume directives.
![image](https://user-images.githubusercontent.com/73624416/147793355-121498f4-2d75-4caf-8bf3-e2e2e327fda6.png)
- After each change to /etc/default/grub I am rebuilding my GRUB config and dracut image.  Since I am using CentOS, I'm running `grub2-mkconfig -o /boot/grub2/grub.cfg` followed by `dracut --force`
- When I initiate ssh with the dropbear ssh key, during the second boot phase, I get the expected dracut shell

My best guess as to what's going on is that the MBR partition, being only 512 bytes (???) doesn't have access to the Dropbear ssh binary, since that is on the encrypted drive. (???) However, if I provide the passphrase in plaintext somewhere outside of the main drive (e.g. MBR?), that completely defeats the purpose of encrypting the drive to guard against physical compromise of the machine (...no?)

Any help would be greatly appreciated!

**Comment by ahesford** [comment]
Sounds like you are relying on GRUB to unlock your volume to find a kernel and initramfs. The solution is to move your /boot out of the encrypted volume and configure GRUB to boot from the unencrypted kernel. At this point, the initramfs can assume responsibility for unlocking your volume and it will launch an SSH server as expected.

**Comment by billyJoePiano** [comment]
Thanks @ahesford !  I figured it was something like that, but I'm having a hard time finding any resources about how to do that...
