### ISSUE TITLE
dropbear binary missing from initrd

### ISSUE THREAD

**Issue by pathetic-lynx** [dracut-crypt-ssh/dracut-crypt-ssh#54]
I am using Archlinux with `uefi=true`.

The dropbear binary is missing from my initrd but the crypt-ssh module is included. Do I have to manually include the dropbear binary?

**Comment by ahesford** [comment]
Drop bear is sought and installed at https://github.com/dracut-crypt-ssh/dracut-crypt-ssh/blob/master/modules/60crypt-ssh/module-setup.sh#L119-L125

Should installation fail, dracut should complain. Are you seeing any error messages when you run `dracut`?

**Comment by pathetic-lynx** [comment]
Yes my bad, I did not bother to carefully read the output somehow assuming the module installation succeeded since I saw it in `lsinitrd`. The issue was that `dropbearconvert` was complaining about the format of the SYSTEM host key files.

PR incoming :)
