### ISSUE TITLE
Module should ensure cryptsetup is installed

### ISSUE THREAD

**Issue by copyrights** [dracut-crypt-ssh/dracut-crypt-ssh#56]
`unlock` requires `cryptsetup`. It is not ensured that `cryptsetup` gets installed.

E.g. in my current test with OEL9. As `systemd` module is used neither `systemd` nor `90crypt` installs `cryptsetup`.

Therefore `unlock` fails with ambiguous message `Could not open luks-...` .

This is maybe related to #11

**Comment by ahesford** [comment]
This module has utility apart from the `unlock` tool. People may wish to launch an SSH server (*e.g.*, in a ZFSBootMenu image or in another ZFS unlocking setup, as I do) without needing `cryptsetup`. The module is and should remain optional.

**Comment by copyrights** [comment]
Thanks for clarifying :+1:
