### ISSUE TITLE
Explicitly depend on /sbin/cryptsetup

### ISSUE THREAD

**Issue by a-crate** [dracut-crypt-ssh/dracut-crypt-ssh#58]
/sbin/cryptsetup is required for the unlock binary to function, but not explicitly depended on on the module. In certain configurations (this happened to me on gentoo with systemd) it's possible for the cryptsetup binary to not be needed by another crypt modules, leaving this one non-functional. The latest version of the systemd initramfs modules doesn't need cryptsetup.

**Comment by ahesford** [comment]
This has come up before, *e.g.*, in https://github.com/dracut-crypt-ssh/dracut-crypt-ssh/issues/56. There are applications for this module beyond using `unlock`, so hard-depending on something that enables this optional functionality is not appropriate.

The right fix is

```bash
install_items+=" /sbin/cryptsetup "
```

in your dracut configuration.

**Comment by uriesk** [comment]
@ahesford 
since this line can be added to `/etc/dracut.conf.d/crypt-ssh.conf`, why not make a small commented out explenation?

```
# if you make use of the unlock command and cryptsetup isn't available in your initramfs, force it to be included by uncommenting the following line:
# install_items+=" /sbin/cryptsetup "
```

**Comment by ahesford** [comment]
f8127c19dc935bd6c607e123e219bd2fc8a35e50
