### ISSUE TITLE
booting linux6.2 breaks console_auth helper if CONFIG_LEGACY_TIOCSTI is unset

### ISSUE THREAD

**Issue by Piraty** [dracut-crypt-ssh/dracut-crypt-ssh#59]
as expected...

https://www.openwall.com/lists/oss-security/2023/03/14/2

**Comment by dramez** [comment]
Hi,

Do you know how to fix this dracut-crypt-ssh solution on Fedora 37/38 ?

EDIT:
I found a workaraund.

After connecting to server type in console:
sysctl -w dev.tty.legacy_tiocsti=1

and continue with default command:
console_auth

After providing password system boots for me (6.2.10-300.fc38.x86_64)


Hope it will be fixed somehow soon

**Comment by ahesford** [comment]
@dramez please test #60 if possible.

**Comment by dramez** [comment]
> 



> @dramez please test #60 if possible.

I added delivered by you line  to dropbear-start.sh, rerun dracut -f and it works again now!

Thanks for really fast answer :)

**Comment by ahesford** [comment]
Thanks for testing!
