### ISSUE TITLE
[Fedora 38] unlock - Could not find /sbin/cryptsetup

### ISSUE THREAD

**Issue by davidfrickert** [dracut-crypt-ssh/dracut-crypt-ssh#69]
On Fedora 38 the `console_auth` and `console_peek` functions work nicely, but can't get `unlock` to work...

After ssh-ing into the machine:

```
-sh-5.2#   echo 'insert-pasword-here' | unlock
Warning: Unable to lock memory, are you root?
Could not find /sbin/cryptsetup
```

`console_auth` works though:

```
-sh-5.2# console_auth 
Passphrase: 
-sh-5.2# Connection to 192.168.2.100 closed by remote host.
Connection to 192.168.2.100 closed.
ssh: connect to host 192.168.2.100 port 222: Connection refused
```

**Comment by ahesford** [comment]
Looks like the `unlock` program isn't finding `cryptsetup` at `/sbin/cryptsetup`. Before attempting to use `unlock`, can you see where `cryptsetup` is located (if it exists at all)? Have you added `cryptsetup` to your initramfs?

**Comment by davidfrickert** [comment]
Didn't modify anything on `dracut` so I guess not? Not exactly sure on how to add `cryptsetup` to initramfs.
I searched for it in `/sbin`, `/usr/bin` and `/bin` and didn't find it.

**Comment by davidfrickert** [comment]
Well, i just saw that the module config has a commented line to add `/sbin/cryptsetup` that i didn't uncomment. Probably that.

**Comment by davidfrickert** [comment]
Maybe in the README when you talk about the `unlock` command add a note that this config needs to be changed?

**Comment by uriesk** [comment]
Usually people have to edit the config file and will necessarily stumble upon it:
https://github.com/dracut-crypt-ssh/dracut-crypt-ssh/commit/f8127c19dc935bd6c607e123e219bd2fc8a35e50

...i guess the README could point at it a bit harder.
