### ISSUE TITLE
Design Discussion #1: Keys and module-setup.sh

### ISSUE THREAD

**Issue by fandingo** [dracut-crypt-ssh/dracut-crypt-ssh#72]
I've recently started using this project, and the the key management side has been quite the pain because of the utilities executed by `module-setup.sh`. 

I wanted to get some feedback before I start altering  *the* major script of this project. 

**Complaint:** I don't like that `module-setup.sh` executes `dropbearconvert` and `ssh-keygen` commands automatically. It introduces unneeded dependencies.

Key Conversion
----------------

Yeah, it is kind of weird and unexpected that dropbear requires PEM-formatted keys, compared to openssh. But, this seems easily solvable in the documentation (i.e. `crypt-ssh.conf` comments). I don't think it's this module's responsibility to convert the keys to the proper format. 

Key Information
-----------------

The calls to `ssh-keygen` to print fingerprint and bubblebabble are completely unnecessary. 

I get that `ssh-keygen` is necessary for `=GENERATE` config options, but if I've already got my keys setup, and in the correct format, why do I need a useless `openssh` package? 

Proposal
======

* `module-setup.sh` no longer converts path-specified keys to PEM format.
* `module-setup.sh` does not print key fingerprints or bubblebabble at all. 
* Improve the config file documentation and README.md to more clearly specify that PEM keys are required and provide help on how to create and/or convert them.
* However, when `crypt-ssh.conf` has `=GENERATE` config options, `ssh-keygen` will be used to generate the appropriate key pair type. 
* Improve documentation to clearly specify that `ssh-keygen` is required for `=GENERATE`. 
* For `=SYSTEM`, I would prefer that they are assumed to be PEM and copied without conversion, but I don't have a strong opinion. I imagine that swapping to a "non-conversion" code-path would cause the largest user disruption, so I'm sensitive to that. 

Objective: A user who has created their host and auth keys in the proper PEM and specified them in `crypt-ssh.conf` should not need to have either `dropbearconvert` or `ssh-keygen` programs to complete the dracut build.

**Comment by ahesford** [comment]
I generally agree with your complaints and proposed solution, except the "SYSTEM" option should always use `dropbearconvert` to preserve continuity and let people use their host keys (although I think this is a bad idea). 

A third option (maybe "NATIVE") should be added and made the default. This can look for keys in`/etc/dropbear`. When matching keys are found, they should be assumed to be in the correct format and copied verbatim into the initramfs image. If native keys are expected but not found, GENERATE behavior (or SYSTEM; whatever the current default behavior is) could be a one-time fallback, creating new keys in `/etc/dropbear` that will be reused the next time.

Take a look at https://github.com/ahesford/mkinitcpio-dropbear/blob/master/dropbear_install to see how I think keys should be handled.

**Comment by fandingo** [comment]
Thanks for the quick reply. I'll start working on a code patch to get feedback and do the doc updates separately. 

I agree with your stance on the `SYSTEM` mode. I'm not a fan of a `NATIVE` mode. The "scanning" sounds cumbersome, and unless there's a lot of logic with calls to `dropbearconvert`/`ssh-keygen`/`openssl`, it's just uses hard-coded file names. I think users that want that behavior should specify the filenames in the `dracut.d/ssh-crypt.conf` file.

**Comment by ahesford** [comment]
I'm not sure that you understand the purpose of NATIVE mode:
1. If keys exist as `/etc/dropbear/dropbear_${keyType}_host_key`, use them.
2. If keys don't exist there, then either
    - Convert OpenSSH keys at `/etc/ssh/ssh_host_${keyType}_key` to dropbear keys at `/etc/dropbear/dropbear_${keyType}_host_key`, or
    - Generate new dropbear-compatible keys at `/etc/dropbear/dropbear_${keyType}_host_key`.

Which alternative is chosen in Step 2 will depend on whatever the module default is currently; I don't have it in front of me to check. There is no need for "a lot of logic" or "cumbersome" scanning; just check if the expected file exists, and either use it or take a one-time, one-step process to put it there.

**Comment by fandingo** [comment]
I don't have strong opinions on `NATIVE`. I understand your description, and my opinion is: this module needs less auto-conversion and auto-detection, rather than more. There should be an easy path for users that don't want to configure anything, and there is real value in supporting that. Beyond that user case, users should produce the properly formatted keys and specify the paths in the config file. 

Again, I don't really care about `NATIVE`. I'm trying to provide patches to simplify and decouple this modules in ways that respect traditional use.
