### ISSUE TITLE
Reusing some parts of the code and relicensing them 

### ISSUE THREAD

**Issue by ylabidi** [dracut-crypt-ssh/dracut-crypt-ssh#80]
Hi,

I'd like to know if I can reuse some of the code in this repository and license it under GPL-3. My package will solely focus on simplifying the module and providing early boot ssh availability without the helpers and any extraneous dependencies and checks.

Thanks a lot!

**Comment by ahesford** [comment]
No. You may use the project source in accordance with the terms of its GPL 2 license, but we will not consider changes to the license.

**Comment by ylabidi** [comment]
Fair enough. Thanks.
