### ISSUE TITLE
Update COPR and add EPEL 10 as build target

### ISSUE THREAD

**Issue by duritong** [dracut-crypt-ssh/dracut-crypt-ssh#81]
Could you update the builds in COPR https://copr.fedorainfracloud.org/coprs/uriesk/dracut-crypt-ssh/ and also add EPEL 10 as build target?

I can help in case this is necessary...

**Comment by ahesford** [comment]
COPR builds are unsupported, third-party contributions.

**Comment by uriesk** [comment]
I am the third party behind this copr, i will update.
I follow changes of this repository via RSS and i still somehow missed that there were commits this month.

Thanks
