### ISSUE TITLE
SELinux support

### ISSUE THREAD

**Issue by ginkel** [dracut-crypt-ssh/dracut-crypt-ssh#9]
Hi there,

I am having major difficulties getting this to work under CentOS 7.3 when SELinux is enabled (enforcing, targeted). Should this theoretically work out of the box?

Thanks,
Thilo

**Comment by ginkel** [comment]
I need to correct my theory: Not SELinux seems to be the culprit, but there is a good chance of about 50% that issuing the `unlock` command (with the correct passphrase on STDIN) will not cause the boot to proceed.

**Comment by breed808** [comment]
Perhaps try `/usr/bin/console_auth` as mentioned in #4 ?

**Comment by ginkel** [comment]
@breed808 Thanks for the hint. As it turned out the cause for the erratic behavior was that I only enabled SELinux after the OS installation and this lead to a reboot where my automated installation script did not expect one (and promptly did not unlock the LUKS partition). dracut-crypt-ssh is working like expected.
